insert into {$prefix}user (username,userpass,importer) values ('admin','e10adc3949ba59abbe56e057f20f883e',1)
insert into {$prefix}group (groupname,importer) values ('系统管理组',1)
insert into {$prefix}groupmanager (groupid,userid,importer) values (1,1,1)
insert into {$prefix}usergroup (userid,groupid,importer) values (1,1,1)
insert into {$prefix}rule (rulename,parentruleid,layer,importer,ruleorder,ruleimg) values ('权限管理',0,1,1,1,'ico/rulemanage.gif')
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('用户浏览',1,'system/user.php',2,1,1)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('用户权限分配',1,'system/userrule.php',2,1,2)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('组浏览',1,'system/group.php',2,1,3)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('组权限分配',1,'system/grouprule.php',2,1,4)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('角色管理',1,'system/role.php',2,1,5)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('菜单浏览',1,'system/rule.php',2,1,6)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('附加值',1,'system/attach.php',2,1,7)
insert into {$prefix}rule (rulename,parentruleid,layer,importer,ruleorder,ruleimg) values ('系统信息',0,1,1,2,'ico/sysinfo.gif')
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('欢迎页',9,'user/user.php',2,1,1)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('系统配置',9,'system/sysconfig.php',2,1,2)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('用户配置',9,'user/userconfig.php',2,1,3)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('信息反馈',9,'system/feedback.php',2,1,4)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('日志信息',9,'system/loginfo.php',2,1,5)
insert into {$prefix}rule (rulename,parentruleid,ruleurl,layer,importer,ruleorder) values ('信息栏',9,'system/message.php',2,1,6)
insert into {$prefix}role (rolename,importer) values ('系统管理员',1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,2,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,3,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,4,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,5,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,6,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,7,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,8,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,10,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,11,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,12,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,13,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,14,1,1,1,1,1,1)
insert into {$prefix}rolerule (roleid,ruleid,issuperuser,canbrowse,canappend,canmodify,candelete,importer) values (1,15,1,1,1,1,1,1)
insert into {$prefix}logtype (logtypename,importer) values ('系统信息',1)
insert into {$prefix}logtype (logtypename,importer) values ('操作记录',1)
insert into {$prefix}log (logtypeid,srcuserid,content) values (1,1,'欢迎使用本系统')
insert into {$prefix}grouprole (groupid,roleid,importer) values (1,1,1)
insert into {$prefix}otherrule (isrule,ruleid,configvarname,configname,configvalue,configtype,configdefault,importer) values(1,3,'Extends','允许附加权下放','请选择=-1#允许=1#拒绝=0','select','-1',1)
insert into {$prefix}otherrule (isrule,ruleid,configvarname,configname,configvalue,configtype,configdefault,importer) values(1,5,'Extends','允许附加权下放','请选择=-1#允许=1#拒绝=0','select','-1',1)
insert into {$prefix}otherrule (isrule,ruleid,configvarname,configname,configvalue,configtype,configdefault,importer) values(1,3,'DispRule','允许查看别人权限','请选择=-1#允许=1#拒绝=0','select','-1',1)
insert into {$prefix}otherrule (isrule,ruleid,configvarname,configname,configvalue,configtype,configdefault,importer) values(1,5,'DispRule','允许查看别人权限','请选择=-1#允许=1#拒绝=0','select','-1',1)
insert into {$prefix}otherrule (isrule,ruleid,configvarname,configname,configvalue,configtype,configdefault,importer) values(1,13,'Accept','允许接受并处理反馈','请选择=-1#允许=1#拒绝=0','select','-1',1)
insert into {$prefix}otherrule (issystemvar,configvarname,configname,configvalue,configtype,configdefault,importer) values (1,'firstLoginChangePass','强制用户第一次登录必须更改密码','是=1#否=0','radio','1',1)
insert into {$prefix}otherrule (issystemvar,configvarname,configname,configvalue,configtype,configdefault,importer,maxlength) values (1,'changeRuleLogout','权限更改时，强迫用户重新登录','是=1#否=0','radio','1',1,2)
insert into {$prefix}otherrule (issystemvar,configvarname,configname,configvalue,configtype,configdefault,importer,maxlength) values (1,'allowErrorLoginNums','允许登录错误尝试次数','次','text','5',1,2)
insert into {$prefix}otherrule (issystemvar,configvarname,configname,configvalue,configtype,configdefault,importer,maxlength) values (1,'loginTimeOut','登录超时秒数','秒','text','28800',1,6)
insert into {$prefix}otherrule (issystemvar,configvarname,configname,configvalue,configtype,configdefault,importer,maxlength) values (1,'loginErrorTimeOut','登录错误超时秒数','秒','text','3600',1,6)
insert into {$prefix}otherrule (issystemvar,configvarname,configname,configvalue,configtype,configdefault,importer) values (1,'loginErrorLog','记录登录错误信息','是=1#否=0','radio','1',1)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer) values ('defaultPage','用户默认页','[sql]select rulename,ruleid from {$prefix}rule where ruleid in(当前权限) and ruleurl is not null','select','10',1)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer) values ('allowGroupManagerLogi','接受组长以本人身份登录','接受=1#拒绝=0','radio','1',1)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer,maxlength) values ('allowErrorManagerLogi','允许未经允可登录的次数','次数','text','3',1,2)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer) values ('logGroupManagerActio','跟踪组长登录后的操作明细','是=1#否=0','radio','0',1)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer) values ('singleLogi','单一登录（拒绝在两台机器同时登录）','是=1#否=0','radio','0',1)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer) values ('amdinMainStyle','管理页面框架风格','网站风格=style1#Windows风格=style2','select','style1',1)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer) values ('delete','是否显示删除提示','是=1#否=0','radio','1',1)
insert into {$prefix}otherrule (configvarname,configname,configvalue,configdefault,configtype,importer) values ('topButtons','顶部工具栏','[sql]select rulename,ruleid from {$prefix}rule where ruleid in(当前权限) and ruleurl is not null','[sql]select ruleid from {$prefix}rule where rulebigimg is not null and ruleid in(当前权限) and ruleurl is not null','checkbox',1);
insert into {$prefix}otherrule (configvarname,configname,configvalue,configdefault,configtype,importer) values ('leftButtons','左侧工具栏','[sql]select rulename,ruleid from {$prefix}rule where ruleid in(当前权限) and ruleurl is not null','[sql]select ruleid from {$prefix}rule where ruleid in(当前权限) and ruleimg is not null and ruleurl is not null','checkbox',1);
insert into {$prefix}otherrule (configvarname,configname,configvalue,configtype,configdefault,importer,maxlength) values ('MainLeftWidth','左侧工具栏宽度','px','text','300',1,2)
insert into {$prefix}attachrule (userorgrouporrole,userorgrouporroleid,addordel,ruleid,baserule,otherruleid,importer,configvalue) values(3,1,1,3,'00000',1,1,1)
insert into {$prefix}attachrule (userorgrouporrole,userorgrouporroleid,addordel,ruleid,baserule,otherruleid,importer,configvalue) values(3,1,1,5,'00000',2,1,1)
insert into {$prefix}attachrule (userorgrouporrole,userorgrouporroleid,addordel,ruleid,baserule,otherruleid,importer,configvalue) values(3,1,1,3,'00000',3,1,1)
insert into {$prefix}attachrule (userorgrouporrole,userorgrouporroleid,addordel,ruleid,baserule,otherruleid,importer,configvalue) values(3,1,1,5,'00000',4,1,1)
insert into {$prefix}attachrule (userorgrouporrole,userorgrouporroleid,addordel,ruleid,baserule,otherruleid,importer,configvalue) values(3,1,1,13,'00000',5,1,1)